In [ ]:
import numpy as np
import pandas as pd

def sigmoid(x):
  return 1 / (np.exp(-x) + 1)

In [ ]:
train_data = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
train_output = np.array([[0,1,1,0]]).T

In [ ]:
train_output

array([[0],
       [1],
       [1],
       [0]])

In [ ]:
train_output.shape

(4, 1)

In [ ]:
train_output.size

4

In [ ]:
train_output.ndim

2

In [ ]:
#generate weights
#model a single neuro with 3 input connections and 1 output connection
#we asssign random wights
np.random.seed(1)
weights = 2 * np.random.random((3,1)) -1
weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [ ]:
for i in range(1000):
  output = sigmoid(np.dot(train_data,weights))

In [ ]:
def SCG(x):
  return x * (1-x)

In [ ]:
output.shape

(4, 1)

In [ ]:
for i in range(5000):
  inputs = train_data
  output = sigmoid(np.dot(inputs,weights))
  error = train_output - output 
  adjusted_weights = error * SCG(output)
  weights += np.dot(inputs.T,adjusted_weights)

In [ ]:
print(weights)
print('===============')
print(output)

[[ 8.95950703]
 [-0.20975775]
 [-4.27128529]]
[[0.01377293]
 [0.98877541]
 [0.99087996]
 [0.011196  ]]
